### ISSUE TITLE
Deauther Not Working

### ISSUE THREAD

**Issue by keko01** [M1z23R/ESP8266-EvilTwin#16]
First of all, health to your labor. Unfortunately, the deauther feature, which is the most important feature, does not work. Good work mate, looking forward to this one to be resolved first and a new one.

**Comment by M1z23R** [comment]
I've just released v2, feel free to try with v2.
In v1, I forgot to add a switch for channel so probably only APs on channel 1 could get deauthed.

**Comment by AsherPhan** [comment]
Although channel hopping is working and I verified, the Deauther still not working

**Comment by adierc** [comment]
if use original board driver, deauth wont work, i use driver from another source it work just fine

**Comment by cakralithium** [comment]
deauther and evil twin its work..
enter wifi server M1z23R 
push start deauthing and start evil twin
sign in wifi fake.. and  192.168.4.1..and wait for  got password ... stop deauthing
